In [1]:
import numpy as np

In [10]:
arreglo = np.random.randint(0, 40, 5)
arreglo

array([ 0, 14, 10, 28, 33])

In [11]:
ordenado = np.sort(arreglo)
ordenado

array([ 0, 10, 14, 28, 33])

In [12]:
reverse = ordenado[::-1]
reverse

array([33, 28, 14, 10,  0])