In [1]:
import numpy as np

In [2]:
valores = np.random.randint(0, 30, 5)
valores

array([ 9, 18, 26, 13, 28])

In [4]:
valores2 = np.insert(valores, 2, 50)

In [6]:
valores3 = np.append(valores, 500)

In [7]:
np.delete(valores, -1)


array([ 9, 18, 26, 13])

In [8]:
np.delete(valores, 0)

array([18, 26, 13, 28])

In [9]:

arreglo_A = np.random.randint(0, 30, 5)
arreglo_B = np.random.randint(0, 30, 5)


In [10]:
nuevo_arreglo = np.concatenate( [arreglo_A, arreglo_B] )
nuevo_arreglo

array([25, 14, 12, 17, 25, 28,  6, 19,  3, 28])