Where y Select: son instrucciones para filtar basado en una consulta con comandos

In [1]:
import numpy as np

In [2]:
edad = np.random.randint(0, 70, 30)
edad

array([53,  5, 10, 26, 62, 57, 41, 24, 47, 42, 35, 15, 68, 13, 56, 16, 12,
       45,  1, 23, 47, 68, 59, 65, 43, 19, 10, 11,  8, 21])

Where: selecciona elementos de un array basado en una condicion

In [3]:
np.where(
    edad > 10,
    'Edad valida',
    'Edad no validad'
)

array(['Edad valida', 'Edad no validad', 'Edad no validad', 'Edad valida',
       'Edad valida', 'Edad valida', 'Edad valida', 'Edad valida',
       'Edad valida', 'Edad valida', 'Edad valida', 'Edad valida',
       'Edad valida', 'Edad valida', 'Edad valida', 'Edad valida',
       'Edad valida', 'Edad valida', 'Edad no validad', 'Edad valida',
       'Edad valida', 'Edad valida', 'Edad valida', 'Edad valida',
       'Edad valida', 'Edad valida', 'Edad no validad', 'Edad valida',
       'Edad no validad', 'Edad valida'], dtype='<U15')

In [4]:
Temperatura = np.random.randint(-100, 100, 50)
Temperatura

array([-96,  20, -83, -81,  42,   1,  94,  31, -60,   0, -89,  32,  13,
        12, -64, -97,  96, -19,  94, -93, -62, -85,  92,  44, -17,   7,
       -68, -82,  85,  12,  25, -64,  54, -29, -45,  95,  44, -93, -93,
        72,   7, -85, -18, -23,  57,  91, -22,  96,  37,  28])

In [5]:
t_calor = np.where(Temperatura > 27)
t_calor

(array([ 4,  6,  7, 11, 16, 18, 22, 23, 28, 32, 35, 36, 39, 44, 45, 47, 48,
        49]),)

Select: se basa en condiciones mas detalladas 

In [6]:
condiciones = [
    (Temperatura < 0),
    (Temperatura > 13) | (Temperatura < 17),
]

opciones = [
    "congelado",
    "frio",
]

In [9]:
np.select(condiciones, opciones)

array(['congelado', 'frio', 'congelado', 'congelado', 'frio', 'frio',
       'frio', 'frio', 'congelado', 'frio', 'congelado', 'frio', 'frio',
       'frio', 'congelado', 'congelado', 'frio', 'congelado', 'frio',
       'congelado', 'congelado', 'congelado', 'frio', 'frio', 'congelado',
       'frio', 'congelado', 'congelado', 'frio', 'frio', 'frio',
       'congelado', 'frio', 'congelado', 'congelado', 'frio', 'frio',
       'congelado', 'congelado', 'frio', 'frio', 'congelado', 'congelado',
       'congelado', 'frio', 'frio', 'congelado', 'frio', 'frio', 'frio'],
      dtype='<U9')