Una matriz es una conjunto de datos de 2 dimensiones, distibuidos en filas y columnas.

In [8]:
import numpy as np

In [9]:
mi_matriz = np.array([
    [1,  2,   3,  4,  5, 66],
    [11, 22, 33, 44, 55, 66],
    [34, 54, 45, 21, 78, 99] 
    ])

In [10]:
mi_matriz.ndim

2

El resultado es (Filas, Columnas)

In [11]:
mi_matriz.shape

(3, 6)

Obtener el valor de una posicion

In [12]:
mi_matriz

array([[ 1,  2,  3,  4,  5, 66],
       [11, 22, 33, 44, 55, 66],
       [34, 54, 45, 21, 78, 99]])

In [ ]:
mi_matriz[0, 0]

In [13]:
mi_matriz[2, 5]

99

crear un sub-arreglo

In [14]:
nueva_matriz = mi_matriz[1, :4]
nueva_matriz

array([11, 22, 33, 44])

In [15]:
nueva_matriz = mi_matriz[2, 4:]
nueva_matriz

array([78, 99])

In [16]:
nueva_matriz = mi_matriz[1, [0, 4]]
nueva_matriz

array([11, 55])