In [1]:
import numpy as np

In [2]:
data = np.random.randint(0, 70, 30)
data

array([56, 45, 50, 38, 18, 43, 29, 28, 44, 49, 51, 63, 13, 35, 13, 51, 16,
       59, 62, 64, 56, 44,  4, 59, 40, 67, 52,  2,  8, 25])

Salvar la data en un archivo y ruta

In [3]:
np.savetxt('data.txt', data)

In [4]:
np.savetxt('data.csv', data, delimiter=',')

Salvar en una ruta especifica

In [5]:
np.savetxt('/Users/danyzambrano/Downloads/data.txt', data)

In [ ]:
np.savetxt('/Users/danyzambrano/Downloads/data.txt', data, fmt='%i')

In [6]:
np.savetxt('/Users/danyzambrano/Downloads/data.csv', data, fmt='%i')

Cargar un archivo

In [10]:
np.loadtxt('/Users/danyzambrano/Downloads/data.csv')

array([56., 45., 50., 38., 18., 43., 29., 28., 44., 49., 51., 63., 13.,
       35., 13., 51., 16., 59., 62., 64., 56., 44.,  4., 59., 40., 67.,
       52.,  2.,  8., 25.])

In [8]:
np.loadtxt('data.csv')

array([56., 45., 50., 38., 18., 43., 29., 28., 44., 49., 51., 63., 13.,
       35., 13., 51., 16., 59., 62., 64., 56., 44.,  4., 59., 40., 67.,
       52.,  2.,  8., 25.])