In [4]:
import numpy as np

In [5]:
mi_Arreglo = np.random.randint(0, 20, 5)
mi_Arreglo

array([19,  7,  9, 16, 12])

Defino una funcion

In [7]:
def operacion(valor):
    return (valor * 2)


In [8]:
for elemento in mi_Arreglo:
    print( operacion(elemento) )

38
14
18
32
24


Vectorize retorna un ojecto array de una funcion que no es array.

In [9]:
vector = np.vectorize(operacion)
vector(mi_Arreglo)

array([38, 14, 18, 32, 24])

In [10]:
vector2 = np.vectorize(lambda valor: (valor * 2 ))
vector2(mi_Arreglo)

array([38, 14, 18, 32, 24])

Otro Ejemplo de Vectorize

In [11]:
mi_Arreglo2 = np.random.randint(0, 30, 5)
mi_Arreglo2

array([ 8, 10,  9, 19, 24])

In [12]:
def myfunc(a, b):
    if a > b:
        return a - b
    else:
        return a + b

In [13]:
vfunc = np.vectorize(myfunc)
resultado = vfunc(mi_Arreglo2, 3)
resultado

array([ 5,  7,  6, 16, 21])