Un arreglo es un conjunto finito de valores del mismo tipo de dato.

In [6]:
import numpy as np

La longitud del arreglo no se puede modificar.
Una vez definido se queda como esta.

In [7]:
miArreglo = np.array([1, 2, 3, 4, 5, 6])
miArreglo

array([1, 2, 3, 4, 5, 6])

In [8]:
type(miArreglo)

numpy.ndarray

In [9]:
miArreglo.size

6

Con Shape puedes conocer las dimensiones del arreglo

In [10]:
miArreglo.shape

(6,)

sumar un arreglo con una constante

In [12]:
miArreglo2 = np.array([1, 2, 3, 4, 5, 6])
valor_A = miArreglo2 + 20
valor_B = miArreglo2 - 20
valor_C = miArreglo2 * 20
valor_D = miArreglo2 / 20

In [13]:
valor_A

array([21, 22, 23, 24, 25, 26])

In [14]:
valor_B

array([-19, -18, -17, -16, -15, -14])

Se puede indicar el tipo de dato en la creacion del arreglo

In [15]:
miArreglo4 = np.array([-1, 0, 1, 2, 3, 4, 5, 6], dtype=bool)
miArreglo4

array([ True, False,  True,  True,  True,  True,  True,  True])

In [16]:
miArreglo5 = np.array([-1, 0, 1, 2, 3, 4, 5, 6], dtype=float)
miArreglo5

array([-1.,  0.,  1.,  2.,  3.,  4.,  5.,  6.])

In [17]:
miArreglo6 = np.array([-1, 0, 1, 2, 3, 4, 5, 6], dtype=np.complex_)
miArreglo6

array([-1.+0.j,  0.+0.j,  1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j,  5.+0.j,
        6.+0.j])

Crear Arreglos basado en Rangos

In [18]:
miArreglo7 = np.arange(0, 100)
miArreglo7

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [19]:
miArreglo8 = np.zeros(20)
miArreglo8

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [20]:
miArreglo9 = np.zeros(20, dtype=int)
miArreglo9

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
miArreglo10 = np.ones(20)
miArreglo10

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [22]:
miArreglo11 = np.ones(20, dtype=int)
miArreglo11

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

Crear arreglos con data basura aleatoria por el sistema, solo es para rellenar la data

In [23]:
miArreglo12 = np.empty(20)
miArreglo12

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

Crear arreglos con numeros aleatorios entre un rango definido

In [31]:
miArreglo13 = np.random.randint(0, 150, 10)
miArreglo13

array([  5,  60, 135,  34,  57,  58, 101, 148,  11,  28])

Obtener valores del arreglo

In [32]:
miArreglo13[0]

5

In [33]:
miArreglo13[5]

58

In [34]:
miArreglo13[-1]

28

Modificar valores del arreglo

In [35]:
miArreglo13[0] = 12
miArreglo13[5] = 15
miArreglo13

array([ 12,  60, 135,  34,  57,  15, 101, 148,  11,  28])

Crear Sub-Arreglos

In [ ]:
miArreglo14 = np.random.randint(0, 150, 10)
miArreglo14

In [ ]:
miArreglo14[0:6]

In [ ]:
miArreglo14[:6]

In [ ]:
miArreglo14[6:]

In [ ]:
miArreglo14[6::3]

In [ ]:
miArreglo14

In [ ]:
miArreglo14[[1, 3, 5, 8]]

Obtener un nuevo arreglo atravez del filtrado booleano

In [ ]:
miArreglo14

In [ ]:
miArreglo14[[True, False, True, False, True, True, False, True, False, True]]