Copias y Vistas

Copias: Es un nuevo arreglo que posee los mismos objetos del original

Vistas: Es un arreglo que apunta al arreglo original

In [3]:
import numpy as np

In [4]:
arreglo_Original = np.arange(0, 15)
arreglo_Original

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Copia del arreglo

In [5]:
arreglo_Nuevo = arreglo_Original.copy()
arreglo_Nuevo

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
id(arreglo_Original), id(arreglo_Nuevo)

(4399698192, 4399388720)

In [7]:
arreglo_Nuevo[0] = 44
arreglo_Original, arreglo_Nuevo

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]),
 array([44,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]))

Vista del arreglo

In [8]:
arreglo_vista = arreglo_Original.view()
arreglo_vista

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
id(arreglo_Original), id(arreglo_vista)

(4399698192, 4473159280)

In [10]:
arreglo_vista[0] = 55
arreglo_Original, arreglo_vista

(array([55,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]),
 array([55,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]))

Como saber el origen del arreglo?

In [11]:
id( arreglo_vista.base )

4399698192