Filtros y Condiciones se refiere al uso de operadores logicos y relacionales

In [9]:
import numpy as np

In [10]:
mi_arreglo = np.random.randint(0, 200, 30)
mi_arreglo

array([ 43, 124,  46,  80, 191,  12,  15,  85,  18, 192, 184, 163, 135,
       178, 189,  99,  54, 128,  66, 168,  58,  14,   9,  98, 123,  73,
        33,  95,  55,  73])

In [11]:
mi_arreglo > 40

array([ True,  True,  True,  True,  True, False, False,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False,  True,  True,  True, False,
        True,  True,  True])

In [12]:
mi_arreglo < 20

array([False, False, False, False, False,  True,  True, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True, False, False, False, False,
       False, False, False])

In [13]:
mi_arreglo == 92

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False])

In [14]:
mi_arreglo[mi_arreglo >= 40]

array([ 43, 124,  46,  80, 191,  85, 192, 184, 163, 135, 178, 189,  99,
        54, 128,  66, 168,  58,  98, 123,  73,  95,  55,  73])

In [15]:
mi_arreglo[(mi_arreglo > 60) & (mi_arreglo < 100)]

array([80, 85, 99, 66, 98, 73, 95, 73])

In [16]:
mi_arreglo[(mi_arreglo == 20) | (mi_arreglo == 50) | (mi_arreglo == 80)]
mi_arreglo

array([ 43, 124,  46,  80, 191,  12,  15,  85,  18, 192, 184, 163, 135,
       178, 189,  99,  54, 128,  66, 168,  58,  14,   9,  98, 123,  73,
        33,  95,  55,  73])

Validar si todos los elementos cumplen con la condicion

In [17]:
np.all(mi_arreglo > 60)

False

In [18]:
np.all(mi_arreglo < 100)

False

In [19]:
np.all(mi_arreglo == 80)

False

Any valida que si por lo menos unos cumple

In [20]:
np.any( mi_arreglo > 60)

True

In [21]:
np.any( (mi_arreglo > 60) & (mi_arreglo < 200))

True