Transposicion: es intercambiar filas por columnas y viceversa.
sirve para redimensionar la matriz para calculos

Se emplea a menudo para multiplicar matrices, ya que las dimensiones deben ser iguales en esa operacion.

In [1]:
import numpy as np

In [2]:
mi_matriz = np.array([
    [1,  2,   3,  4,  5, 66],
    [11, 22, 33, 44, 55, 66],
    [34, 54, 45, 21, 78, 99] 
    ])

In [5]:
valor = mi_matriz.T
valor

array([[ 1, 11, 34],
       [ 2, 22, 54],
       [ 3, 33, 45],
       [ 4, 44, 21],
       [ 5, 55, 78],
       [66, 66, 99]])

In [6]:
valor.shape

(6, 3)

In [4]:
mi_matriz.shape

(3, 6)

Transposicion de una matriz de 1D

In [9]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [10]:
a.T

array([1, 2, 3, 4, 5])